### ISSUE TITLE
Risk Assessment & Risk Management (RMP)

### ISSUE THREAD

**Issue by instamine** [Serum-390/godzilla#15]
- Following the template provided in the link:
 https://drive.google.com/drive/folders/1bGDF6MlBXSKN0fcYGCe6ZyIvETwXe_6k

**Comment by JustinLohKingWei** [comment]
Completed for Sprint 1 . Located in google drive  https://drive.google.com/folderview?id=1h56OKt3lBDXvySx2VaaZt18O5gSvYXKh
