### ISSUE TITLE
Release Plan (Sprint #2 planning)

### ISSUE THREAD

**Issue by instamine** [Serum-390/godzilla#18]
- Breakdown User Stories
- Over/under estimation of the number and difficulty of user stories plan
- Acceptance tests should be passed at the end of the next sprint.

**Comment by obonobo** [comment]
Closed by Ruochen, docs in Google Drive:
<https://drive.google.com/drive/folders/1YZB_ftHkq07XNLxfk52ynEZ8T1tAJQWJ>
